_wandb:
    value:
        cli_version: 0.21.0
        e:
            nyk381zusnqc9z2r0sm3qmqdy2btlk1n:
                args:
                    - --seed
                    - "42"
                    - --pretrained_model_name_or_path
                    - data/flux
                    - --vae_model_path
                    - data/flux
                    - --cache_dir
                    - data/.cache
                    - --dataset_config
                    - dataset_config/dream_scene.yaml
                    - --gradient_checkpointing
                    - --train_batch_size
                    - "2"
                    - --num_latent_t
                    - "1"
                    - --sp_size
                    - "1"
                    - --train_sp_batch_size
                    - "2"
                    - --dataloader_num_workers
                    - "4"
                    - --gradient_accumulation_steps
                    - "12"
                    - --max_train_steps
                    - "300"
                    - --learning_rate
                    - "1e-5"
                    - --mixed_precision
                    - bf16
                    - --checkpointing_steps
                    - "40"
                    - --allow_tf32
                    - --cfg
                    - "0.0"
                    - --output_dir
                    - data/outputs/grpo
                    - --h
                    - "720"
                    - --w
                    - "720"
                    - --t
                    - "1"
                    - --sampling_steps
                    - "16"
                    - --eta
                    - "0.3"
                    - --lr_warmup_steps
                    - "0"
                    - --sampler_seed
                    - "1223627"
                    - --max_grad_norm
                    - "1.0"
                    - --weight_decay
                    - "0.0001"
                    - --use_hpsv2
                    - --num_generations
                    - "12"
                    - --shift
                    - "3"
                    - --use_group
                    - --ignore_last
                    - --timestep_fraction
                    - "0.6"
                    - --init_same_noise
                    - --clip_range
                    - "1e-4"
                    - --adv_clip_max
                    - "5.0"
                codePath: fastvideo_edited/train_grpo_flux_kontext.py
                codePathLocal: fastvideo_edited/train_grpo_flux_kontext.py
                cpu_count: 20
                cpu_count_logical: 20
                cudaVersion: "12.2"
                disk:
                    /:
                        total: "1080579129344"
                        used: "1001160122368"
                email: yaoliliu8@gmail.com
                executable: /home/ubuntu/miniconda3/envs/dancegrpo/bin/python
                git:
                    commit: 0e03965ad1a64b790e0df38768ff4dbd1b9fb2b6
                    remote: git@github.com:yaoliliu/DanceGRPO-kontext.git
                gpu: NVIDIA A100-SXM4-40GB
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-380bd885-a847-c1c5-0ddd-29aa71e1ea87
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-4d27c021-2a26-2bf3-36f2-7dab4a975629
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-eded71b8-d7c9-68eb-4833-6400023a0acd
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-SXM4-40GB
                      uuid: GPU-f32b0eaf-9ceb-919b-8d84-7e7b1d6685a3
                host: ubuntu-d95
                memory:
                    total: "270252085248"
                os: Linux-6.2.0-34-generic-x86_64-with-glibc2.35
                program: fastvideo_edited/train_grpo_flux_kontext.py
                python: CPython 3.10.18
                root: /home/ubuntu/lyl/DanceGRPO-kontext
                startedAt: "2025-07-31T02:04:56.663729Z"
                writerId: nyk381zusnqc9z2r0sm3qmqdy2btlk1n
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 63
                - 71
                - 80
                - 83
                - 98
            "2":
                - 1
                - 11
                - 41
                - 49
                - 63
                - 71
                - 80
                - 83
                - 98
            "3":
                - 16
            "4": 3.10.18
            "5": 0.21.0
            "6": 4.53.3
            "12": 0.21.0
            "13": linux-x86_64
adv_clip_max:
    value: 5
allow_tf32:
    value: true
cache_dir:
    value: data/.cache
cfg:
    value: 0
checkpointing_steps:
    value: 40
clip_range:
    value: 0.0001
dataloader_num_workers:
    value: 4
dataset_config:
    value: dataset_config/dream_scene.yaml
dit_model_name_or_path:
    value: null
ema_decay:
    value: 0.995
ema_start_step:
    value: 0
eta:
    value: 0.3
fsdp_sharding_startegy:
    value: full
gradient_accumulation_steps:
    value: 12
gradient_checkpointing:
    value: true
h:
    value: 720
ignore_last:
    value: true
init_same_noise:
    value: true
learning_rate:
    value: 1e-05
logging_dir:
    value: logs
loss_coef:
    value: 1
lr_num_cycles:
    value: 1
lr_power:
    value: 1
lr_scheduler:
    value: constant_with_warmup
lr_warmup_steps:
    value: 0
master_weight_type:
    value: fp32
max_grad_norm:
    value: 1
max_train_steps:
    value: 300
mixed_precision:
    value: bf16
num_generations:
    value: 12
num_latent_t:
    value: 1
output_dir:
    value: data/outputs/grpo
precondition_outputs:
    value: false
pretrained_model_name_or_path:
    value: data/flux
resume_from_checkpoint:
    value: null
sampler_seed:
    value: 1223627
sampling_steps:
    value: 16
seed:
    value: 42
selective_checkpointing:
    value: 1
shift:
    value: 3
sp_size:
    value: 1
t:
    value: 1
timestep_fraction:
    value: 0.6
train_batch_size:
    value: 2
train_sp_batch_size:
    value: 2
use_cpu_offload:
    value: false
use_group:
    value: true
use_hpsv2:
    value: true
use_pickscore:
    value: false
vae_model_path:
    value: data/flux
w:
    value: 720
weight_decay:
    value: 0.0001
